spring:
  profiles:
    include: db
    active: test
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    time-zone: "GMT+8"
  application:
    name: CloudServer

server:
  port: 8761
  cloud:
    gateway:
      routes:
        - id: RegistrationSystem
          uri: lb://registration
          predicates:
            - Path=/team/**
        - id: TicketSystem
          uri: lb://ticket
          predicates:
            - Path=/ticket/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
